### ISSUE TITLE
Build action fails during fontbaking

### ISSUE THREAD

**Issue by kosbarts** [kosbarts/Oi#10]
I push the new file and I get the build fails with this error during fontbakery report:

Error: font-bakery Action failed during fontbakery execution attempt with error: The process '/opt/hostedtoolcache/Python/3.8.18/x64/bin/fontbakery' failed with exit code 1

@RosaWagner do you know why this happens?

**Comment by RosaWagner** [comment]
Hi @kosbarts, I am in a sabbatical and no longer contracted by Google (I'm pregnant 🎉), maybe try @emmamarichal can help?

**Comment by kosbarts** [comment]
@RosaWagner that's amazing news! Congratulations. Sleep now that you can!

@emmamarichal how are you? Can you have a look at this and tell me if you know why it happens?

**Comment by kosbarts** [comment]
@davelab6, @simoncozens

Any ideas why the build fails with this message?

Error: font-bakery Action failed during fontbakery execution attempt with error: The process '/opt/hostedtoolcache/Python/3.8.18/x64/bin/fontbakery' failed with exit code 1

https://github.com/kosbarts/Oi/actions/runs/7475117263

**Comment by simoncozens** [comment]
OK, so:

* You are using [f-actions/font-bakery](https://github.com/f-actions/font-bakery/) to run fontbakery within your GitHub Actions file.
* fontbakery itself has recently changed to exit with an error exit code if there are any FAILs; not unreasonable, exit codes are a good way to signal success/failure back to other command line tools.
* The version of f-actions/font-bakery you are using (specifically, you're using f-actions/fontbakery@v1) doesn't know about this change and considers an exit status of 1 to mean OH MY EVERYTHING HAS GONE WRONG.
* Does the latest version of f-actions/font-bakery understand these exit statuses? I don't know. It doesn't look like it from my attempts to read the source, but I'm not familiar with this repo.

So: Try updating f-actions/font-bakery to `f-actions/font-bakery@v3` in your workflow. If that doesn't fix it, please open an issue in `f-actions/font-bakery`.

**Comment by kosbarts** [comment]
@simoncozens Thanks so much for looking into this. I upgraded the action to the @v3 as you suggested but unfortunately I got the same message.

**Comment by simoncozens** [comment]
OK. This has got rid of the ERRORs, but you still have a FAIL (dotted circle). I think this is a f-actions/font-bakery bug, as it should not crash the workflow just for FAILs.  A workaround is to add `continue-on-error: true` to the font-bakery action, like so:

```
      - name: Check with FontBakery
        uses: f-actions/font-bakery@v3
        continue-on-error: true
        with:
          version: "latest"
          subcmd: "check-googlefonts"
          args: "-C --succinct --loglevel WARN --ghmarkdown fonts/report.md"
          path: "fonts/ttf/*.ttf"
```
