### ISSUE TITLE
Build with gftools builder

### ISSUE THREAD

**Issue by RosaWagner** [kosbarts/Oi#2]
The building tool is finished !
https://github.com/googlefonts/gftools/tree/master/Lib/gftools/builder

You just need gftools in a venv
You just add a config.yaml which looks like that:
```
    sources:
      - Oi.glyphs
    outputDir: "../fonts"
    familyName: Oi
```
And you just run from the sources: `$ gftools builder config.yaml`
